// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu2Odx8m4ft8mwhIrng3xRNMqDDrAZyeQ',
    appId: '1:652593698682:web:b116af389e8a17c96ae8c3',
    messagingSenderId: '652593698682',
    projectId: 'flash-b458d',
    authDomain: 'flash-b458d.firebaseapp.com',
    storageBucket: 'flash-b458d.firebasestorage.app',
    measurementId: 'G-MB04EB6Q18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIGh2CkWoQ4Y2yZ7tm9vM7UKc-kviOqtY',
    appId: '1:652593698682:android:eeff82f0f91e569f6ae8c3',
    messagingSenderId: '652593698682',
    projectId: 'flash-b458d',
    storageBucket: 'flash-b458d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkYwbD4ashlM8nxc7IqAenmYy4gb7_QIw',
    appId: '1:652593698682:ios:0f6225cba1ed56ee6ae8c3',
    messagingSenderId: '652593698682',
    projectId: 'flash-b458d',
    storageBucket: 'flash-b458d.firebasestorage.app',
    iosBundleId: 'com.example.datVeXe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkYwbD4ashlM8nxc7IqAenmYy4gb7_QIw',
    appId: '1:652593698682:ios:0f6225cba1ed56ee6ae8c3',
    messagingSenderId: '652593698682',
    projectId: 'flash-b458d',
    storageBucket: 'flash-b458d.firebasestorage.app',
    iosBundleId: 'com.example.datVeXe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu2Odx8m4ft8mwhIrng3xRNMqDDrAZyeQ',
    appId: '1:652593698682:web:70e8f1a8b38d52936ae8c3',
    messagingSenderId: '652593698682',
    projectId: 'flash-b458d',
    authDomain: 'flash-b458d.firebaseapp.com',
    storageBucket: 'flash-b458d.firebasestorage.app',
    measurementId: 'G-3QN9FCY97W',
  );
}
